alias ls="ls -ahvlG --color"
alias open="xdg-open"
alias sys="sudo systemctl"
alias journal="sudo journalctl"
alias dmesg="sudo dmesg"
alias apt="sudo apt"
alias pacman="sudo pacman"
alias service-status="sudo systemctl list-units --type=service --state=loaded --no-pager"
