alias ls="ls -ahvlG --color"
alias open="xdg-open"
alias systemctl="sudo systemctl"
alias journalctl="sudo journalctl"
alias apt="sudo apt"
alias pacman="sudo pacman"
alias service-status="sudo systemctl list-units --type=service --state=loaded --no-pager"
